from rest_framework.urls import path
from .views import *


urlpatterns = [
    path('filter/', CarFilterView.as_view()),
    path('exclude/', CarExcludeView.as_view()),
    path('value/', CarValuesView.as_view()),
    path('valuelist/', CarValuesListView.as_view()),
    path('annotate/', CarAnnotateView.as_view()),
    path('order/', CarOrderByView.as_view()),
    path('reverse/', CarReverseView.as_view()),
    path('distinct/', CarDistinctView.as_view()),
    path('none/', CarNoneView.as_view()),
    path('union/', CarUnionView.as_view()),
    path('intersection/', CarIntersectionView.as_view()),
    path('difference/', CarDifferenceView.as_view()),
    path('select/', CarSelectRelatedView.as_view()),
    path('prefetch/', CarPrefetchView.as_view()),
    path('defer/', CarDeferView.as_view()),
    path('only/', CarOnlyView.as_view()),
    path('using/', CarUsingView.as_view()),
    path('lock/', CarLockView.as_view()),
    path('raw/', CarRawView.as_view()),
    path('and/', CarAndView.as_view()),
    path('or/', CarOrView.as_view()),
    path('c/', CarCreateView.as_view()),
    path('owner/', OwnerCreateView.as_view()),
    path('list/', CarListView.as_view()),
    path('listo/', OwnerListView.as_view()),


    path('listsql/', CarListSQLView.as_view()),
    path('listosql/', OwnerListSQLView.as_view()),
    path('filtersql/', CarFilterSQLView.as_view()),
    path('excludesql/', CarExcludeSQLView.as_view()),
    path('ordersql/', CarOrderBySQLView.as_view()),
    path('distinctsql/', CarDistinctSQLView.as_view()),
    path('reversesql/', CarReverseBySQLView.as_view()),
    path('valuesql/', CarValuesSQLView.as_view()),
    path('valuelistsql/', CarValuesListSQLView.as_view()),
    path('annotatesql/', CarAnnotateSQLView.as_view()),
    path('unionsql/', CarUnionSQLView.as_view()),
    path('intersectionsql/', CarIntersectionSQLView.as_view()),
    path('differencesql/', CarDifferenceSQLView.as_view()),
    path('selectsql/', CarSelectRelatedSQLView.as_view()),
    path('prefetchSql/', CarSelectRelatedSQLView.as_view()),
    path('defersql/', CarDeferSQLView.as_view()),
    path('onlysql/', CarOnlySQLView.as_view()),
    path('locksql/', CarSelectForUpdateSQLView.as_view()),
    path('andsql/', CarAndSQLView.as_view()),
    path('orsql/', CarOrSQLView.as_view()),
]